### ISSUE TITLE
separate body of main function into smaller functions that

### ISSUE THREAD

**Issue by anaderix** [AshishDavid/AI-Membrane-Calculation#13]
do computations for each file:
https://github.com/AshishDavid/AI-Membrane-Calculation/blob/c6e4cd2e4cbd93bde37055556f0392e1dedff60b/main.py#L101-L174

print results:
https://github.com/AshishDavid/AI-Membrane-Calculation/blob/c6e4cd2e4cbd93bde37055556f0392e1dedff60b/main.py#L176-L219

save result:
https://github.com/AshishDavid/AI-Membrane-Calculation/blob/c6e4cd2e4cbd93bde37055556f0392e1dedff60b/main.py#L221-L255

also those functions should not use any global variables - just arguments. Perhaps you need to wrap all the state variables into a single data class (https://stackoverflow.com/questions/47955263/what-are-data-classes-and-how-are-they-different-from-common-classes)

**Comment by AshishDavid** [comment]
Fixed!
